drewhsu86/Boxed-All-Bulk-Cart

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Home/Home.css
- client/src/components/Home/Home.js
- client/src/components/ProductDetails/Image/Images.js
- client/src/components/ProductDetails/Info/Info.js
- client/src/components/ProductDetails/ProductDetails.js
- client/src/components/ProductDetails/RelatedItems/RelatedItems.css
- client/src/components/ProductDetails/RelatedItems/RelatedItems.js
- client/src/components/ProductDetails/Reviews/Reviews.css
- client/src/components/ProductDetails/Reviews/Reviews.js
- client/src/components/data.json
- client/src/components/shared/Layout/Layout.js
- client/src/components/shared/Nav/Nav.js
- client/src/index.js
added some small changed to the home page
added Image, Info, RelatedItems, and Reviews component folders to the ProductDetail page
added more info to ProductDetails components
> Dre - Home

- app.js
- controllers/index.js
- db/index.js
- helpers/index.js
- models/products.js
- models/users.js
- node_modules/bcrypt/package.json
- node_modules/body-parser/package.json
- node_modules/cors/package.json
- node_modules/express/package.json
- node_modules/jsonwebtoken/package.json
- node_modules/mongodb/package.json
- node_modules/mongoose/package.json
- node_modules/morgan/package.json
- node_modules/nodemon/package.json
- package.json
- routes/index.js
- seed/index.js
- server.js
Backend operational, includes CRUD and authentication.
> Tm backend

- models/products.js
- seed/index.js
- seed/products.json
> Tom Moliterno

- client/package-lock.json
- client/package.json
- client/src/components/Carousel/Carousel.css
- client/src/components/Home/Home.js
- client/src/components/Home/HomeCarousel/CarouselHome.css
- client/src/components/Home/HomeCarousel/CarouselHome.js
- client/src/components/ProductDetails/Image/Images.css
- client/src/components/ProductDetails/Image/Images.js
- client/src/components/ProductDetails/ProductDetails.js
- client/src/index.js
Created and implemented the carousel in the Home component page
> AG - Home Carousel

- client/src/components/Home/Home.js
- client/src/components/Home/HomeCarousel/CarouselHome.css
- client/src/components/Home/HomeCarousel/CarouselHomeWithButtons.css
- client/src/components/Home/HomeCarousel/CarouselHomeWithButtons.js
- client/src/components/Home/HomeCarousel/banners.json
damn son where'd you find this CarouselHomeWithButton
> Ah carousel home with button

- client/src/components/ProductDetails/Image/Images.css
changed and arranged the images component to correct alignment
small tweaks
> Dre - Images component update

- client/src/components/Home/Home.js
- client/src/components/Home/HomeCarousel/CarouselHome.js
- client/src/components/ProductDetails/Info/Info.css
- client/src/components/ProductDetails/Info/Info.js
- client/src/components/ProductDetails/ProductDetails.js
- client/src/components/data.json
- client/src/index.js
I added a bunch of stuff to the Info component from the main ProductDetail component page.
I completed it the info section for the most part, I just didn't add the dropdown menus and the progress bar thing on the bottom. 
I imported the Open Sans font and added it to the main Index.js component. 
I removed the route from the bootstrap CSS in the Index.js and moved it to the Home.js component instead.
> Dre - Info Component Styling

- controllers/index.js
- package.json
- routes/index.js
3 new routes and controller functions, please test in postman
> ah-backend calls for: multiple IDs, by category, by category & subcategory

- client/src/components/ProductDetails/ProductDetails.css
- client/src/components/ProductDetails/ProductDetails.js
check the js file because i made a topRow class that sets the vertical height so that the two line up from the top of the page
> ah - changes to productDetails js and css to make two flex columns

- client/src/App.js
- client/src/components/Admin/AdminNav.js
- client/src/components/Admin/LoginStatus.js
- client/src/components/Admin/Signin.js
- client/src/components/Admin/Signup.js
- client/src/components/Admin/index.js
- client/src/services/apiConfig.js
completed sign in and sign up (and a mini-nav) for the admin pages
> ah-reactAdminPages first pass

- client/src/App.js
- client/src/components/ProductDetails/Image/Images.js
- client/src/components/ProductDetails/Info/Info.js
- client/src/components/ProductDetails/ProductDetails.js
- client/src/components/ProductDetails/RelatedItems/RelatedItems.js
- client/src/services/products.js
added changes to routes for productdetail page
> Product Detail Routing

- client/src/App.js
- client/src/components/Home/Home.js
- client/src/components/shared/Layout/Layout.js
- client/src/components/shared/Nav/Nav.js
- client/src/components/shared/Nav/Nav1.css
- client/src/components/shared/Nav/Nav1.js
- client/src/components/shared/Nav/Nav2.css
- client/src/components/shared/Nav/Nav2.js
- client/src/components/shared/Nav/Nav3.css
- client/src/components/shared/Nav/Nav3.js
- client/src/index.js
changed the routes for the top nav a bit in the Layout component and …
…placed it in the Home componentinstead
added three layers of nav for the top bar
added a bit of styling to each nav component
linked a couple of pages to their corresponding links
> Dre - Top Nav

- client/src/components/Carousel/Carousel.css
- client/src/components/Carousel/ProductThumb.jsx
- client/src/components/Home/HomeCarousel/CarouselHomeWithButtons.css
- client/src/components/Home/HomeCarousel/CarouselHomeWithButtons.js
- client/src/components/Home/HomeCarousel/banners.json
- client/src/components/ProductDetails/Image/Images.css
- controllers/index.js
- routes/index.js
- seed/products.json
product thumbnail titles and images are links, and also the home carousel now has a shop now button
> Ah product thumbs as links

- client/src/App.js
- client/src/components/Home/Home.css
- client/src/components/Home/Home.js
- client/src/components/Home/HomeCarousel/CarouselHomeWithButtons.css
- client/src/components/Home/HomeModal/HomeModal.css
- client/src/components/Home/HomeModal/HomeModal.js
added the HomeModal component to the Home component
i was not sure how to make it a popup on load so i created a button instead
minor tweaks to the home carousel and evened it out
need to make an "X" close button on modal
> Dre - Home Modal

- client/src/components/Admin/Admin.css
- client/src/components/Admin/AdminNav.js
- client/src/components/Admin/Create.js
- client/src/components/Admin/EditOrDelete.js
- client/src/components/Admin/Manage.js
- client/src/components/Admin/Signin.js
- client/src/components/Admin/Signup.js
- client/src/components/Admin/index.js
- controllers/index.js
- node_modules/dotenv/CHANGELOG.md
- node_modules/dotenv/LICENSE
- node_modules/dotenv/README.md
- node_modules/dotenv/config.js
- node_modules/dotenv/lib/cli-options.js
- node_modules/dotenv/lib/env-options.js
- node_modules/dotenv/lib/main.js
- node_modules/dotenv/package.json
- node_modules/dotenv/types/index.d.ts
- node_modules/dotenv/types/test.ts
- node_modules/dotenv/types/tsconfig.json
- node_modules/dotenv/types/tslint.json
- package-lock.json
- package.json
- routes/index.js
crud functions finished for admin side
can: signup, signin, add a product, search for a product, edit a product, delete a product
> Ah react admin pages2 crud

- client/src/components/Home/HomeModal/HomeModal.css
- client/src/components/Home/HomeModal/HomeModal.js
- client/src/index.js
1. no longer has open button on home page: automatically runs 
2. does not double render or render on pages that are not home 
3. changed close button to a slightly styled [X] button
> ah fixed issues with home modal

- .gitignore
- client/src/components/Admin/Admin.css
- client/src/components/Admin/Manage.js
- node_modules/dotenv/package.json
- process.env
changed token_key to be an env variable (and will change the key as well)
> pre-deployment branch with some fixes

- client/src/App.js
- client/src/components/Carousel/ProductThumb.jsx
- client/src/components/ShoppingCart/Cart.js
- client/src/components/ShoppingCart/CartItem.js
- client/src/components/ShoppingCart/ShoppingCart.css
- client/src/components/ShoppingCart/index.js
- helpers/index.js
uses local storage
can change quantity, remove item
can hide window
next steps: connect functions to other components so we can open and add to the cart
> AH - shopping cart prototype

- client/src/categories.json
- client/src/components/Products/Banner.js
- client/src/components/Products/Cat.js
- client/src/components/Products/Products.css
- client/src/components/Products/Products.jsx
I may need to adjust the width once the rest of Products.js is styled.
> LS -  bulk banner

- client/src/components/ProductDetails/Info/Info.css
- client/src/components/ProductDetails/ProductDetails.css
- client/src/components/ProductDetails/ProductDetails.js
- client/src/components/ProductDetails/RelatedItems/RelatedItems.css
- client/src/components/ProductDetails/RelatedItems/RelatedItems.js
- client/src/components/ProductDetails/Reviews/Reviews.css
- client/src/components/RelatedItemsDummyData.json
added dummy data to the related items component
spacing came out weird on the related items section but I think it looks alright?
fixed spacing issues with components
added some final styling to the product details page
> Dre - Product Details Styling Update 

- client/src/App.js
- client/src/components/Products/Cat.js
- client/src/components/Products/DisplayNav.js
- client/src/components/Products/Products.jsx
- client/src/components/Products/SubCat.js
> LS - display cat/subcat

- client/src/App.js
- client/src/components/LoginPage/Login.css
- client/src/components/LoginPage/Login.js
created a login page sort of like the mockup
definitely not responsive at all.. view in full screen mode
did not link it to anything on the page, you have to type /login in the url
just made it without function
> Dre - Login Page

- client/src/components/ProductDetails/CheckoutModal/CheckoutModal.css
- client/src/components/ProductDetails/CheckoutModal/CheckoutModal.js
- client/src/components/ProductDetails/Info/Info.js
- client/src/components/ProductDetails/ProductDetails.js
- client/src/components/ProductDetails/RelatedItems/RelatedItems.js
created checkout modal on Product Detail page
triggers with add to cart on click
> Dre - Checkout Modal
